/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Adept': '熟练',
	'adept': '熟练',
    'advise notables': '通知著名人士',
    'abstraction': '抽象',
    'clean stables': '清理马厩',
    'Clear': '清理',
    'close': '关闭',
    'combat': '战斗',
    'craft gem': '工艺宝石',
    'craft rune': '工艺符文',
    'dark mode': '黑暗模式',
    'Deep Pockets': '深口袋',
    'Sell Herbs': '出售草药',
    'sell gem': '出售宝石',
    'sell scroll': '出售卷轴',
    'Tomes': '著作',
	'max Tomes': '著作上限',
    'rest': '休息',
    'reset': '重置',
    'reset wizard': '重置此巫师',
    'resting': '休息中',
    'pouch': '小袋',
    'max pouch': '小袋上限',
    'player': '玩家',
    'save': '保存',
    'load': '加载',
    'LOADING DATA...': '加载数据...',
    'main': '主界面',
    'max gold': '黄金上限',
    'manas': '魔法能量',
    'get save': '下载存档',
    'hall save': '下载大厅存档',
    'event': '事件',
    '[Drop Save]': '[读档]',
    'souls': '灵魂',
    'max souls': '灵魂上限',
    'Stop All': '全部停止',
    'stamina': '耐力',
    'gems': '宝石原石',
    'unlock': '解锁',
    'gold': '黄金',
    'loot': '掠夺',
    'working from home.': '在家工作。',
    'water gem': '水之宝石',
    'wizard': '巫师',
    'wood pipe': '木管',
    'A tattered scroll': '一个破烂的卷轴',
    'air gem': '空气宝石',
    'air runes': '气符文',
    'max air runes': '气符文上限',
    'max runes': '符文上限',
    'airaffinity': '空气亲和力',
	'airsource': '空气来源',
	'air': '气',
	'max air': '气上限',
    'alchemist': '炼金术士',
    'alembic': '蒸馏器',
    'alkahest': '剧情',
    'almagest': '天文学大成',
    'fire gem': '火之宝石',
    'fire sign': '火象星座',
    'grind bones': '研磨骨头',
    'grind': '研磨',
    'name': '名字',
    'title': '头衔',
    'level': '等级',
    'life': '生命值',
    'rest life': '生命值恢复',
	'max life': '生命上限',
    'light gem': '光之宝石',
    'max light gem': '光之宝石上限',
    'mage': '法师',
    'exp': '经验值',
    'skill points': '技能点',
    'luck': '幸运值',
    'defense': '防御',
    'dodge': '闪避',
    'damage bonus': '伤害加成',
    'hit bonus': '命中加成',
    'speed': '速度',
    'weapon': '武器',
    'fists': '拳头',
    'resists': '抵抗',
    'distance': '距离',
    'mount': '坐骑',
    'None': '无',
    'purse': '钱包',
    'max purse': '钱包上限',
    'prism': '棱镜',
    'buy scroll': '购买卷轴',
    'purchase gem': '购买宝石',
    'read palms': '看手相',
    'research': '研究',
    'rune stones': '符文石',
    'max rune stones': '符文石上限',
    'scribe scroll': '抄写卷轴',
    'You buy a strange scroll from a travelling peddlar. If you could only decipher the cryptic symbols.': '你从一个流动小贩那里买了一幅奇怪的画卷。但愿你能破译这些神秘的符号。',
    'Choose': '选择',
    'class': '课程',
	'job, class': '职业，课程',
    'hp': '生命',
    'scrolls': '卷轴',
    'sell': '出售',
    'shadow gem': '暗影宝石',
    'max shadow gem': '暗影宝石上限',
    'Stop': '停止',
    'studying scrolls': '学习卷轴',
    'immunities': '抵抗力',
    'pouch (': '小袋（',
    'upgrades': '升级',
    'travel': '旅行',
    'travel map': '旅行地图',
    'travel pack': '旅行包',
    'travel tent': '旅行帐篷',
    'treat ailments': '治疗疾病',
    'velvet bag': '绒布袋',
    'effects': '效果',
    'End Apprenticeship': '结束学徒制',
    'Energy Transfusion': '能量输入',
    'expanded cellars': '扩大酒窖',
    'Apprenticeship': '学徒制',
    'expedient retreat': '权宜之计撤退',
    'animal companion': '动物伴侣',
    'sublimate lore': '升华知识',
    'Study arcane scrolls': '研究奥术卷轴',
    'Slay Master': '杀戮大师',
    'cost': '成本',
    'Titles': '标题',
    'imbue gem (air': '灌输宝石 (空气',
    'imbue gem (arcane': '灌输宝石 (奥术',
    'imbue gem (fire': '灌输宝石 (火',
    'craft rune (fire': '篆刻符文 (火',
    'craft rune (earth': '篆刻符文 (土',
    'craft rune (air': '篆刻符文 (气',
    'craft rune (water': '篆刻符文 (水',
    'imbue gem (light': '灌输宝石 (光',
    'imbue gem (shadow': '灌输宝石 (暗影',
    'imbue gem (spirit': '灌输宝石 (精神',
    'imbue gem (water': '灌输宝石 (水',
    'imbue gem (nature': '灌输宝石 (自然',
    'imbue stone (earth': '灌输坷垃 (土',
    'gemimbue': '宝石灌输',
    'infused body': '注入体内',
    'inner fire': '内部火',
    'inner light': '内部光',
    'hold seance': '举行集会',
    'holding seance': '集会中',
    'holy candle': '圣烛',
    'home': '家',
    'After paying a small fee, you became apprenticed to a local wizard.': '支付少量费用后，您就成了当地巫师的学徒。',
    'animal handling': '驯养动物',
    'appentice to a notable wizard': '引诱到一个著名的巫师',
    'apple bobbing': '咬苹果',
    'apprentice': '学徒',
    'Apprentice': '学徒',
    'arcana': '奥秘',
    'arcane': '奥术',
    'arcane body': '奥术身体',
    'max arcane body life': '奥术身体生命上限',
    'arcane gem': '奥术宝石',
    'max arcane gem': '奥术宝石上限',
    'arcane orb': '奥术球',
    'arcane thievery': '奥术窃取',
    'arcane trickster': '奥术魔法师',
    'armillary sphere': '浑天仪',
    'auto-save': '自动保存',
    'autonomic mending': '自主修复',
    'bag of holding': '储存宝袋',
    'bag of tricks': '魔法袋',
    'basement': '地下室',
    'battle mage': '战斗法师',
    'Become an apprentice.': '成为一个学徒。',
    'rune pouch': '符文袋',
    'run errands': '跑腿',
	'running errands': '正在跑腿',
    'do chores': '做家务',
    'filch pumpkins': '窃取南瓜',
    'cot': '婴儿床',
    'Done': '完成',
    'earth gem': '土之宝石',
    'equip': '装备',
    'feet': '脚',
    'Find': '寻找',
    'Owned': '已拥有',
    'Unowned': '未拥有',
    'need': '需要',
    'offer services': '提供服务',
    'old nag': '老弱马',
    'poison affinity': '毒性亲和力',
    'progress cost': '进度成本',
    'poison veins': '毒脉',
    'skills': '技能',
    'Promotion': '晋升',
    'Skill Points': '技能点',
    'slot: rest': '插槽：休息',
    'bones': '骨头',
    'max bones': '骨头上限',
    'chant': '歌唱',
	'\n		chant': '歌唱',
	'chanting': '歌唱中',
    'cauldron': '坩埚',
    'Buy': '购买',
    'chest': '胸部',
    'Compile Tome': '编译巨著',
    'crystal mind': '水晶心灵',
    'crystal ball': '水晶球',
    'doomsayer': '末日审判者',
    'Furnishing': '家具',
    'Sell': '出售',
    'Space': '空间',
    'Really brightens up the place.': '确实使这个地方变亮了。',
    'Perfect for robins.': '完美的知更鸟。',
    'potted milkweed': '盆栽的乳草',
    'wishing wells': '许愿井',
    'witch\'s sabbat': '女巫的安息日',
    'trap soul': '灵魂陷阱',
    'workbench': '工作台',
    'water sign': '水象星座',
    'earth sign': '土象星座',
    'wind sign': '风象星座',
    'Mortar and Pestle': '研钵和研杵',
    'Magic Horseshoes': '魔法马蹄铁',
    'Magic circle': '魔法圈',
    'magic circle': '魔法圈',
    'birdcage': '鸟笼',
    'blood gem': '血之宝石',
    'blood mage': '血法师',
    'lvl': '等级',
    'magic heist': '魔法抢劫',
    'mana': '法力',
    'lore': '知识',
    'Prologue': '序言',
    'An idle waif with no prospects to speak of...': '你是一个毫无前途，而又游手好闲的流浪汉...',
    'Keep your money safe.': '保管好你的钱。',
    'seems a tad pricey for a bag.': '对于一个包来说，它似乎有点贵。',
    'it\'s stable employment': '这是项稳定的工作',
    'Gold Coins': '金币',
    'Scroll of arcane lore': '记载着奥术知识的卷轴',
    'Research into the Arcane': '奥术研究',
    'locks': '锁定',
    'max research': '研究上限',
    'standard apprentice work.': '标准的学徒工作。',
    'satchel': '书包',
    'Decent': '正直的',
    'You are turning out to be an upstanding spellcaster.': '你正在变成一名正直的施法者',
    'steal pumpkins from nearby homes': '从附近的人家中偷点南瓜',
    'pumpkins': '南瓜',
    'max pumpkins': '南瓜上限',
    'Carry more scrolls.': '能携带更多卷轴。',
    'max scrolls': '卷轴上限',
    'falconer': '训鹰人',
    'Tend your master\'s owls and falcons.': '照顾导师的猫头鹰及猎鹰。',
    'herbalist': '草药师',
    'herbalism': '草药学',
    'herbalism exp': '草药学经验',
    'Gather herbs for your master\'s potions and alchemy.': '采集草药作为材料来满足导师在药剂和炼金术上的需要。',
    'carve lantern': '刻南瓜灯',
    'smash pumpkin': '打碎南瓜',
    'pumpkin seeds': '南瓜种子',
    'pumpkin carriage': '南瓜马车',
    'jack o\' lantern': '杰克南瓜',
    'max jack o\' lantern': '杰克南瓜上限',
    'seed sack': '种子袋',
    'max pumpkin seeds': '南瓜种子上限',
    'you need to have a word with the sack-maker\'s guild.': '你需要和制袋协会谈谈。',
    'Unlock': '解锁',
    'nothing is more important to a wizard than the depth of their lore.': '对于一个巫师来说，一切都不如知识的深度重要。',
    'If your max gold is not enough to buy a new home, free space for more chests.': '如果你达到黄金上限都买不起新家，腾出点地方买更多的箱子吧。',
    'small chest': '小箱子',
    'Slightly better than sleeping on the floor': '比睡在地板上稍微好点',
    'A small wooden chest.': '一个小木箱。',
    'Switch': '更换',
    'floor space': '房间面积',
    'A small bench for arts and crafts. Necessary for many wizard studies.': '一个用来做各种工艺品的小工作台。许多巫师研究都需要它。',
    'alcove': '小角落',
    'A small corner beneath the stairs of your Master\'s domicile.': '你导师住处的楼梯下方的小角落（译者注：必须购买工作区类型的家具来解锁制造技能，才能继续推进游戏）',
    'max floor space': '最大房间面积',
    'goodbye hayloft.': '再见了，干草棚。',
    'Moving In': '搬家',
    'After taking your savings, your new master grants you a small nook under the stairs.': '在拿走你的积蓄后，你的新导师让你住在楼梯下的角落里。',
    'max inventory': '库存上限',
    'iron chest': '铁箱子',
    'crafting': '制造',
    'an absolutely vital skill for a wizard to craft arcane items.': '对巫师来说，拥有制造奥术物品的能力是极其重要的。（译者注：必须学习该技能，才能继续推进游戏）',
    'workspace': '工作区',
    'rest stamina': '耐力恢复',
    'rest fire': '火恢复',
    'rest manas': '魔法能量恢复',
    'garden': '花园',
    'languages': '语言',
    'max arcana': '奥秘上限',
    'wax candle': '蜡烛',
	'candle': '火烛',
	'max candle': '火烛上限',
    'A tiny glowing candle.': '一根小小的发光的蜡烛。',
    'You no take candle!': '你不能拿走我的蜡烛！',
    'restless nights': '不眠之夜',
    'continue working even while idle': '即使有空闲时间也要不停工作',
    'a good apprentice knows there are 30 hours to the day.': '优秀的学徒明白，一天有30个小时。',
    'focus': '专注',
    'quicken your skills with magic energy.': '用魔法来加速增强你的能力。',
    'Focus': '专注',
    'Profound mystical knowledge': '深奥的神秘知识',
    'scroll rack': '卷轴架',
    'train lore rate': '知识训练速度',
    'books and scrolls are written in many obscure languages. learn as many as possible.': '许多书籍和卷轴都是用各种晦涩难懂的语言书写的。尽可能多的学习各种语言吧。',
    'bind codex': '装订成册',
    'Codices': '手册',
    'codices': '手册',
	'max Codices': '手册上限',
    'Codex of arcane lore': '关于奥术知识的手册',
    'internalize a vast amount of existing knowledge.': '将大量的现有知识吸收成为你的一部分',
    'latticed shelves for easy scroll storage.': '架子上有一个个格子，便于储存卷轴',
    'bookshelf': '书架',
    'A single bookshelf for your books.': '一个专门来放你的书的书架。',
    'scribe': '抄写员',
    'Scribe': '抄写员',
    'Become your master\'s personal scribe.': '成为你导师的私人抄写员。',
    'raw magical energy': '原始的魔法能量',
    'Bind Spellbook': '装订魔法书',
	'binding spells': '装订魔法书',
    'The portal to true magic.': '通往真正魔法之门。',
    'prestidigitation': '变戏法',
    'Why study when you can perform parlor tricks for coin?': '既然你能通过表演一些小把戏来赚钱，那你为什么要学习呢？',
    'spellbook': '魔法书',
    'lore exp': '知识经验值',
    'Book Of Spells': '魔法书',
    'Book of Spells': '魔法书',
    'Under your master\'s critical eye, you compile your very own book of spells.': '在导师挑剔的目光下，你完成了自己的魔法书。',
    'spells': '法术',
    'loom': '织布机',
    'Treasure chest.': '宝箱。',
    'unlocks the art of weaving': '开启编织的艺术',
    'duration': '持续时间',
    'Learn': '学习',
    'lines of arcane energy damage all enemies.': '通过奥术射线攻击所有敌人。',
    'prismatic spray': '棱柱喷射',
    'minor mana': '次级法力',
    'magic missile': '魔法飞弹',
    'lesser mana': '较少法力',
    'weaving': '编织',
    'max crafting': '制造技能上限',
    'Cast': '施放',
    'Memorize': '记忆',
    'Memorized': '已记忆',
    'Level': '等级',
    'Remove': '移除',
    'Alternate Wizard classes of this tier will be locked.': '这一层的其它巫师课程将被锁定。',
    'Confirm': '确认',
    'Cancel': '取消',
    'In return for your new services, your master grants you a small allowance for your studies. The position does require of course, some initial fees...': '作为对你新服务的回报，你的主人会给你一小笔钱去学习。当然，这个职位需要一些初始费用……',
    'Leaky Cellar': '漏水的地窖',
    'adventure': '探险',
    'basin': '水池',
    'Basin of water.': '一池水',
    'water': '水',
    'max water': '水上限',
    'crafting table': '制造桌',
    'Wide table for crafting projects.': '用来制造东西的宽桌。',
    'train crafting rate': '制造训练速度',
    'pedestal': '读书台',
    'A pedestal for reading magic tomes. Improves study habits.': '一个能用来读魔法书的台子。提升你学习的兴趣。',
    'study research': '学习获得的研究',
    'writing desk': '写字台',
    'A desk for working and scribing.': '供工作和书写的桌子.',
    'max languages': '语言等级上限',
    'anatomy': '解剖学',
    'anatomy exp': '解剖学上限',
    'spirit lore': '精神知识',
    'spirit lore exp': '精神知识经验',
	'max spirit lore': '精神知识上限',
    'wood dagger': '木质匕首',
    'leather shortsword': '皮革短剑',
    'the study of physical form.': '对物理形态的研究。',
    'leather jerkin': '皮革上衣',
    'Master Of The Cellar': '酒窖之主',
    'mule': '骡子',
    'herbs': '草药',
    'map stars': '地图星',
    'max nature': '自然上限',
    'max trickery': '诡计上限',
    'heart of stone': '石之心',
    'right': '右',
    'left': '左',
    'ring': '戒指',
    'activity exp': '当前行动经验',
    'max lore': '知识技能上限',
    'train herbalism rate': '草药学训练速度',
    'train alchemy rate': '炼金术训练速度',
    'siver\'s gate': '西弗门',
    'Speak to Birds': '和鸟说话',
    'third eye': '第三只眼',
    'Unequip': '卸下',
    'Use': '使用',
    'Sell All': '全部出售',
    'apple🎃 (': '苹果🎃 (',
    'apple': '苹果',
    'back': '背部',
    'bodies': '尸体',
    'max bodies': '尸体上限',
    'bone dust': '骨粉',
    'coagulate gem (blood': '凝结宝石 (血',
    'cobwebs': '蜘蛛网',
    'max cobwebs': '蜘蛛网上限',
    'coin tricks': '硬币戏法',
    'max magicgems': '成品宝石上限',
    'max gems': '宝石原石上限',
    'max herbs': '草药上限',
    'neophyte': '初学者',
    'Neophyte': '初学者',
    'herb pouch': '草药袋',
    'three-sided coin': '三面硬币',
    'compile bestiary': '编译动物寓言集',
    'compile witchhammer': '编译女巫锤',
    'cooking pot': '蒸煮锅',
    'tenwick\'s travel map': '滕维克旅游地图',
    'trick & treat': '款待&捣蛋',
    'unseen scribe': '无形抄写员',
    'unholy specimens': '邪恶的标本',
    'gather herbs': '收集草药',
    'gem box': '宝石盒',
    'max gem box': '宝石盒上限',
    'nature': '自然',
    'nature gem': '自然宝石',
    'oracle': '神谕',
    'oracular insight': '神谕的洞察力',
    'alchemy': '炼金术',
    'nature lore': '自然知识',
	'max nature lore': '自然知识上限',
	'nature lore exp': '自然知识经验',
    'trickery': '诡计',
    'train trickery rate': '诡计训练速度',
    'earth runes': '土符文',
    'flame runes': '火符文',
    'water runes': '水符文',
	'max earth runes': '土符文上限',
	'max flame runes': '火符文上限',
	'max water runes': '水符文上限',
    'water lore': '水流知识',
    'water lore exp': '水流知识经验',
    'wooden bed': '木床',
    'creeping vine': '匍匐藤蔓',
    'craft phylactory': '工艺植物学',
    'watersource': '水来源',
    'furniture': '家具',
    'funerary rites': '丧葬仪式',
    'trickery exp': '诡计经验',
    'The final step on the twisting stairwell of apprenticeship.': '学徒制如同扭曲盘旋直上的阶梯，你将踏上最后一阶。',
    'who prices these bags?!': '谁给这些袋子定价？',
    'Why does Master charge so many fees?': '师父为何要收取这么多费用？',
    'dissection': '解剖',
    'max dissection': '解剖上限',
    'train dissection rate': '解剖训练速度',
    'lillit\'s spring': '莉莉特之泉',
    'human bones.': '人类的骨头。',
    'a mount that doesn\'t require much training.': '一个不需要太多训练的坐骑。',
    'tradition tells of a spring with enchanted waters. investigations might prove revealing.': '传说有一泓泉水被施与魔法。调查可能会揭示其中的真相。',
    'Pillage Graves': '盗墓',
    'embalming': '尸体保存',
    'max embalming': '尸体保存上限',
    'train embalming rate': '尸体保存训练速度',
    'embalming exp': '尸体保存经验',
    'shadowlore': '暗影学识',
    'shadowlore exp': '暗影学识经验',
    'train shadowlore rate': '暗影学识训练速度',
    'Dig up old graves for magical reagents. These guys are like 300 years old, they won\'t mind.': '挖开古墓来获取魔法材料。这些家伙看起来死了超过三百年了，他们是不会介意的。',
    'it\'s for a good cause.': '这么做是有正当理由的。',
    'virtue': '道德',
    'You sense something buried nearby.': '你感觉到附近埋着什么东西。',
    'hidden cache': '隐藏地点',
    'mana tree': '魔法树',
    'a tree by a magic spring exhibits surprising qualities': '魔法泉旁的一棵树展现出惊人的品质',
    'mystic waters': '神秘的水',
    'water suffused with enchantments': '水中含有魔法',
    'befuddlement': '迷惑',
    'placid grove': '宁静的树林',
    'only the rare glimpse of wildlife breaks the stillness of the grove.': '只有罕见的野生动物一瞥打破了小树林的寂静',
    'every budding mage needs to start somewhere.': '每个初露头角的魔法师都要从某处开始。',
    'bone pendant': '骨质吊坠',
    'wood greaves': '木制护胫',
    'robe': '长袍',
    'amulet': '护身符',
    'sunny field': '阳光旷野',
    'musty library': '发霉的图书馆',
    'dissect cadaver': '解剖尸体',
    'dissect a body for components. only the best pieces will serve.': '解剖身体来获得其中的一部分。只有最好的那部分才能留下来。',
    'skull': '头骨',
    'shadow': '暗影',
    'Various fine gemstones.': '各种精美的宝石。',
    'grind bones into dust': '把骨头磨成灰',
    'a good apprentice spends all their free time in the library. after doing chores, of course.': '一个优秀的学徒会把所有的空闲时间都花在图书馆里。当然，是在做完家务之后。',
    'occult tapestry': '神秘的挂毯',
    'a tapestry with strange, hidden meanings': '一幅有着奇怪的、隐藏深意的挂毯',
    'workbook': '练习书',
    'a book on the practical applications of magic': '一本关于魔法的实际应用的书',
    'magical primer': '魔法读本',
    'an introduction to magical theory.': '有关魔法理论的导论。',
    'dusty chest': '满是灰尘的箱子',
    'A battered, wooden chest.': '一个破旧的木箱。',
    'Goblins, Goblins!': '哥布林，哥布林！',
    'Rumors hint at a camp of goblins in the vicinity. As an aspiring wizard, convention dictates you test your mettle on their lives.': '谣传周边有哥布林的营地。由于你是一名积极的巫师，协会命令你去干掉他们，来证明自己的勇气，',
    'goblin camp': '哥布林营地',
    'arag heights': '阿拉戈高地',
    'barren mountains over arazor': '阿拉佐上方的荒山',
    'eryl eyot': '伊瑞尔之岛',
    'the small and tranquil island is inhabited by an old hermit named thyffr': '这个宁静的小岛上住着一位年老的隐士，他的名字叫瑟夫',
    'Nestled in the fog of the midlands, the village of Hallomar holds a yearly celebration in its pumpkin patch.': '万圣村坐落在中部地区的迷雾当中，每年都会在南瓜地中举办庆祝活动。',
    'hallomar': '万圣村',
    'concentration': '集中',
    'concentration exp': '集中经验',
    'keep your mind and nerves sharp under pressure.': '在压力下保持头脑清醒，神经敏锐。',
    'just don\'t wander too far from the village.': '只是别在离村子太远的地方徘徊。',
    'stony hills': '乱石丘陵',
    'composure': '镇静',
    'composure exp': '镇静经验',
    'remain unfazed under strain.': '在压力下保持镇定。',
    'treffil woods': '崔菲尔之林',
    'these enchanted woods are not particularly dangerous.': '这些魔法森林并没有那么危险。',
    'the pesky creatures are everywhere.': '这种令人厌恶的生物到处都是。',
    'foggy dale': '起雾的山谷',
    'The fog here is so thick, you can\'t see your own hands.': '这里的雾太大了，你连自己的手都看不见。',
    'outright confusion in your studies': '你的研究完全混乱',
    'unease': '不安',
    'a general feeling of unwell': '一种不舒服的感觉',
    'weariness': '疲倦',
    'the fatigue of mental strain': '精神紧张的疲劳',
    'frustration': '挫败感',
    'rising book-throwing urges': '有种把书扔出去的冲动',
    'madness': '疯狂',
    'warping of your mind under magical influences': '在魔法的影响下你的思想逐渐扭曲',
    'pumpkin patch': '南瓜地',
    'In Hallomar\'s autumn fields grow some of the largest pumpkins to be found.': '秋天的万圣村，田地中生长着巨大的南瓜，这种南瓜是别处没有的。',
    'LOOT': '掠夺',
    'cobwebs🎃, pumpkins': '蜘蛛网🎃, 南瓜',
    'haunted glade': '闹鬼的空地',
    'Trees here have an eerie aspect': '这里的树外形非常怪异',
    'Exploring...': '探索中...',
    'starry night': '繁星之夜',
    'a clear sky affords an endless view of the firmament.': '透过晴朗的天空可以看到无尽的苍穹。',
    'Harvest Reveller': '收割者',
    'graveyard': '墓地',
    'hestia\'s cottage': '赫斯提的小屋',
    'Deep in Thangmor forest, the great witch Hestia keeps a small, secluded cabin. On rare occasions she even takes visitors.': '在唐穆尔森林深处，伟大的女巫赫斯提有一个与世隔绝的小木屋。在极少数情况下，她甚至会接待客人。',
    'The graveyard beside Hallomar is nearly abandoned now. Low murmurs and eerie croakings haunt the autumn nights.': '万圣村旁的墓地现在已经快荒废了。秋天的夜晚，这里萦绕着轻声的低语和怪异的叫声。',
    'explore treffil wood': '探索崔菲尔之林',
    'the woods posses many features of interest to the magical scholar.': '这片树林拥有者许多特性，因此吸引了许多魔法学者',
    'allies': '盟友',
    'enemies': '敌人',
    'virtue : evil': '道德:邪恶',
    'evil': '邪恶',
    'stress': '压力',
    'compact mode': '紧凑模式',
    '\r\n			Next Improvement': '下一次提升',
    'Hide Maxed': '隐藏已满',
    'apprentice to a notable wizard': '著名巫师的学徒',
    'garden': '花园',
    'pets': '宠物',
    'bed': '床',
    'max': '最大',
    'max: ∞': '最大：∞',
    'purchase cost': '购买费用',
    'linguisticizing': '语言化',
    'reading lore': '阅读知识',
	'\n\n		progress': '进度',
    'damage': '伤害',
    'dmg': '伤害',
    'dot': '状态',
    'spiritsource': '精神来源',
    'spirit': '精神',
	'max spirit': '精神上限',
    'school': '学院派',	//游戏里应该是指水、火、气、光等这些魔法分类
    'spirit gem': '精神宝石',
    'max spirit gem': '精神宝石上限',
    'Enter': '进入',
    'Retreat': '撤退',
    'astronomy': '天文学',
    'astronomy exp': '天文学经验',
    'enchanting': '附魔',
    'enchanting exp': '附魔经验',
    'max enchanting': '附魔上限',
    'train enchanting rate': '附魔训练速度',
    'enchanting table': '附魔桌',
    'divination': '占卜',
    'lumenology': '荧光知识',
    'lumenology exp': '荧光知识经验',
    'mysticism': '神秘主义',
    'train mysticism rate': '神秘主义训练速度',
    'potion': '药剂',
    'pyromancy': '火焰知识',
    'a compilation of gloomy dwarven drinking songs': '令人沮丧的矮人诗酒歌集',
    'dwarven dirges': '矮人挽歌',
    'a weighty tome of knowledge.': '一个沉重的知识之书。',
    'breviary': '赞美经',
    'train languages rate': '语言的训练速度',
    'lightsource': '光明来源',
    'light': '光',
    'max light': '光上限',
    'max mana': '法力上限',
    'max alchemy': '炼金术上限',
    'firesource': '火焰来源',
    'fire': '火',
    'fireplace': '壁炉',
    'A cozy place for cooking food and brewing potions.': '一个舒适的地方，用于烹饪食物和酿造药水。',
	'earthsource': '土地来源',
    'starsource': '星星来源',
    'shadowsource': '暗影来源',
    'potsource': '药剂来源',
    'dream catcher': '梦境捕捉',
    'fine crucible': '细坩埚',
    'max fire': '火上限',
    'transfusions': '输血',
    'urn': '骨坛',
    'sextant': '六分仪',
    'reliquary': '宝库',
    'A cramped cage for keeping tiny test subjects.': '狭窄的笼子，用于存放微小的测试对象。',
    'rusty cage': '生锈的笼子',
    'terrarium': '玻璃罩',
    'a glass enclosure of dirt, insects, and wormy things.': '灰尘，昆虫和蠕虫的玻璃罩。',
    'earth': '土',
    'wind lore': '大气知识',
    'wind lore exp': '大气知识经验',
    'max wind lore': '大气知识上限',
    'max herbalism': '草药学上限',
    'max pyromancy': '火焰知识上限',
    'max shadowlore': '暗影知识上限',
    'brass candelabra': '黄铜烛台',
    'the knowledge of what has come before reveals what is yet possible.': '对过去发生的事情的认识可以预测将要发生的事情',
    'history': '历史',
    'history exp': '历史经验',
    'Pace your home as you comtemplate the arcane.': '在家中踱步思索奥术',
    'pace': '踱步',
    'pacing': '踱步中',
    'lemurian lexicon': '狐猴词典',
    'interpret the strange whisperings of spirits': '解释精怪们的耳语',
    'sylvan syllabary': '树精音节',
    'card deck': '卡座',
    'ceaseless bellows': '不竭风笛',
    'windchime': '风铃',
    'crystal solidifier': '晶体固化剂',
    'tend animals': '照料动物',
    'occult endurance': '神秘耐力',
    'spin gold': '点石成金',
    'spinning': '正在戳',
    'starcharts': '星图',
    'animal handling exp': '驯养动物经验',
    'max animal handling': '驯养动物上限',
    'max astronomy': '天文学上限',
    'max divination': '占卜上限',
    'max starcharts': '星图上限',
    'train astronomy rate': '天文学训练速度',
    'train divination rate': '占卜训练速度',
    'geomancy': '挖地知识',
    'max earth': '土上限',
    'summoning': '召唤',
    'scrying': '水晶球占卜',
    'scrying exp': '水晶球占卜经验',
    'scry': '水晶球占卜',
	'max summoning': '召唤上限',
    'train summoning rate': '召唤训练速度',
    'max stress': '压力上限',
    'unending tome': '挖坑不填',
    'some books have no end': '有些书写着写着就太监了',
    'max water lore': '水流知识上限',
    'bottomless pitcher': '无底瓶子',
    'celestial globe': '天象仪',
    'cellar': '地窖',
    'chirography': '书法',
    'wateraffinity': '水性亲和',
    'water affinity': '水 性亲和',
    'bestiary': '兽人传说',
    'compendium of magical creatures': '魔法生物纲要',
    'a manual of the human body': '人体手册',
    'coporis fabrica': '人体构造',
	'max anatomy': '解剖学上限',
    'train anatomy rate': '解剖学训练速度',
    'unholy candle': '邪恶火烛',
    'truesight': '真视',
    'max shadow': '暗影上限',
    'spellcraft': '法术学识',
    'max spellcraft': '法术学识上限',
    'max scrying': '水晶球占卜上限',
    'max geomancy': '挖地知识上限',
    'chronomancy': '时间学识',
    'chronomancy exp': '时间学识经验',
    'train chronomancy rate': '时间学识训练速度',
    'max chronomancy': '时间学识上限',
    'charm': '魅惑',
    'conjuration': '召唤学',
    'conjuration exp': '召唤学经验',
    'max conjuration': '召唤学上限',
    'demonology': '恶魔学',
    'max demonology': '恶魔学上限',
    'max lumenology': '荧光知识上限',
    'magic beasts': '魔法生物学',
    'max magic beasts': '魔法生物学上限',
    'planes lore': '飞行知识',
    'planes lore exp': '飞行知识经验',
    'max planes lore': '飞行知识上限',
    'max stamina': '耐力上限',
    'timesplit': '时间分割',
    'tempus': '时源',
    'max tempus': '时源上限',
    'void': '虚空',
    'max void': '虚空上限',
    'max activity': '行动上限',
    'pendulum': '钟摆',
    'timesource': '时间来源',
    'train demonology rate': '恶魔学训练速度',
    'train potions rate': '药剂学训练速度',
    'max potions': '药剂学上限',
    'train scrying rate': '水晶球占卜训练速度',
    'train spellcraft rate': '法术学识训练速度',
    'max mysticism': '神秘主义上限',
    'max reanimation': '复活术上限',
    'reanimation': '复活术',
    'reanimation exp': '复活术经验',
    'train reanimation rate': '复活术训练速度',
    'magicgems': '成品宝石',
    'max bone dust': '骨粉上限',
    'demonic dictionary': '恶魔字典',
    'fazbit\'s fixations': '法兹比的凝视',
    'reveler\'s rite': '适时狂欢',
    'scribe a copy the seminal text in practical alchemy': '抄写一份关于实用炼金术的开创性文本的副本',
    'corivar called fazbit a mad crank. then came begging for his manuals.': '有的人说法兹比是个疯子，然后乞求他的手稿',
    'Dragon Tongue': '龙舌',
    'celerity': '疾速',
    'demonic pact': '恶魔契约',
    'earth soul': '土地之魂',
    'earthaffinity': '土地亲和',
    'evanescence': '消逝',
    'fireaffinity': '火焰亲和',
    'fatalist': '宿命论',
    'swirling globe': '旋转球体',
    'metronome': '节拍器',
    'mendicant': '乞讨',
    'Sacrifice luxury for higher attainments.': '放弃奢华以获得更高的成就感。',
    'long-stem pipe': '长杆管',
    'ghost chains': '鬼链',
    'summon familiar': '召唤恶魔生物',
    'forewarned': '征兆',
    'casgair\'s conjured canopy': '卡斯的魔法斗篷',
    'heresiarch': '异端领袖',
    'ghost compiler': '鬼魂编译员',
    'max ghost compiler': '鬼魂编译员上限',
    'max unseen scribe': '无形抄写员上限',
    'greater arcane body': '巨大奥术身体',
    'max greater arcane body': '巨大奥术身体上限',
    'gryffon': '格里芬',
    'workshop': '车间',
    'void lore': '虚空知识',
    'void lore exp': '虚空知识经验',
    'max void lore': '虚空知识上限',
    'minions': '奴隶',
    'max minions': '奴隶上限',
    'minions maxAllies': '最大奴隶上阵数',
    'max Codices research': '手册的研究上限',
    'fingers': '手指',
    'neck': '颈部',
    'shins': '腿部',
    'waist': '腰',
    'hands': '手',
    'head': '头',
    'murder': '谋杀',
    'blood siphon': '吸血',
    'blood siphon manas': '吸血时恢复魔法能量',
    'blood siphon shadow': '吸血时恢复暗影',
    'blood siphon spirit': '吸血时恢复精神',
    'vile experiment': '卑鄙试验',
	'dissection exp': '解剖经验',
	'divination exp': '占卜经验',
    'charms': '魅惑',
    'max charms': '魅惑上限',
    'train charms rate': '魅惑训练速度',
    'runic lore': '符文学',
    'max runic lore': '符文学上限',
    'outdoors': '户外',
    'prison': '监狱',
    'armssource': '武器来源',
    'stables': '马厩',
	'enchantsource': '附魔来源',
    'ziggurat': '尖塔',
    'weapon rack': '武器架',
    'warding lanterns': '灯笼守卫',
    'vivarium': '活体容器',
    'vault': '拱顶',
    'vat': '缸',
    'codex annihilus': '食书虫',
    'darkmagician': '黑暗魔法师',
    'seer': '先知',
    'enchanter': '附魔师',
    'Enchanter': '附魔师',
    'eat children': '吃小孩',
    'commune': '密谈',
    'bone collector': '骨头收集器',
    'magic skull': '魔法头骨',
    'necromancy': '死灵法术',
    'max necromancy': '死灵法术上限',
    'train necromancy rate': '死灵法术训练速度',
    'necromancer': '死灵法师',
    'thanophage': '邪恶食人魔',
    'This action is not reversible. Continue?': '这个动作不可逆，是否确定？',
    'Hide': '隐藏',
    'Maxed': '达上限',
    'Blocked': '已锁定',
    'Max': '上限',
    'notoriety': '恶名',
    'skill': '技能',
    'hiddenpockets': '隐藏的口袋',
    'world lore': '世界认知',
    'max world lore': '世界认知上限',
    'world lore exp': '世界认知经验',
    'chaos': '混乱',
    'geas': '勇者厄运',
    'advanced gemcraft': '高级宝石工艺',
    'gemcraft': '宝石工艺',
    'Imbue gems continuously as your current activity.': '把灌输宝石改造成活动（即变成屎色背景的按钮），这样它们就可以自动重复进行',
    'runecrafter': '符文工艺',
    'two-way portal': '双向传送门',
    'return to dungeons below your level after making a hasty exit.': 'return to dungeons below your level after making a hasty exit.（看不懂TAT）',	//TODO: try to play
    'wizard\'s hall': '巫师大厅',
    'Wizard\'s Hall': '巫师大厅',
    'Construct a Wizard\'s Hall.': '建造一个巫师大厅',
    'hall prestige': '大厅声望',
    'Hall Prestige': '大厅声望',
    'Chair Empty': '空档位',
    'Begin': '开始',
    'Awaken': '唤醒',
    'Dismiss': '遣散（删除！）',
    'Complete': '已完成',
    'Dungeon': '地牢',
    'Explore': '探索',
    'Activate': '启用',
    'Rest': '休息',
    'hat trick': '帽子戏法',
    'guiding star': '导航星',
    'markhul\'s codex': '马克胡尔的手稿',
    'touching the void': '触摸虚空',
    'siege perilous': '危机围城',
    'four leaf clover': '四叶草',
    'fly': '飞',
    'Purchase freedom from your apprenticeship. You will become an independent practitioner of magic.': '花钱赎身来结束学徒制。您将成为独立的魔法实习者。（译者注：完成之后保存游戏，刷新页面）',
    'tohit': '命中',
    'air mastery': '大气精通',
    'spirit mastery': '精神精通',
    'nature mastery': '自然精通',
    'water mastery': '水流精通',
    'earth mastery': '土地精通',
    'shadow mastery': '暗影精通',
    'arcane mastery': '奥术精通',
    'fire mastery': '火焰精通',
    'light mastery': '光明精通',
    'raven': '乌鸦',
    'summon raven': '召唤乌鸦',
    'hobgoblin': '妖精',
    'summon hobgoblin': '召唤妖精',
    'unicorn': '独角兽',
    'summon unicorn': '召唤独角兽',
    'poison': '毒素',
    'spooky': '惊吓',
    'attack': '攻击',
    'geomancer': '大地术士',
    'hydromancer': '水系术士',
    'wind mage': '空气术士',
    'pyromancer': '火焰术士',
    'warden': '守望者',
    'high mage': '高级法师',
    'highelemental': '高级元素师',
    'spell blade': '法术解剖者',
    'bladelore': '刀具知识',
    'bladelore exp': '刀具知识经验',
    'max bladelore': '刀具知识上限',
    'summoner': '召唤者',
    'Cooldown': '冷却',
    'druid': '德鲁伊',
    'thaumaturge': '神迹创造者',
    'astral seer': '星象预言家',
    'dhrunic wizard': '传说级巫师',
    'mythic wizard': '神话级巫师',
    'Attic Bedroom': '阁楼卧室',
    'Dedicate yourself to putting the world in order.': '致力于让世界井然有序',
    'blue adept': '秩序掌控者',
    'vile': '卑鄙',
    'Murder your master in their sleep.': '趁你的导师在睡觉的时候杀死他（译者注：完成之后保存游戏，刷新页面）',
    'Save heaps of money with the power of evil': '邪恶的力量可以帮你省钱',
    'Lodge at Inn': '旅馆小屋',
    'lodge': '小屋',
    'shop': '小商店',
    'house': '房子',
    'inn': '旅馆',
    'camp': '野营',
    'cave': '洞穴',
    'hut': '棚屋',
    'cottage': '茅屋',
    'elemental': '元素',
    'witchcraft': '巫婆',
    'magic broomstick': '魔法扫帚',
	'naturesource': '自然来源',
    'iron cell': '铁制密室',
    'lattice window': '百叶窗',
    'lattice fence': '栅栏',
    'ornate chest': '华丽的宝箱',
    'bonfire': '篝火',
    'bookcase': '书柜',
    'brazier': '火盆',
    'cairn': '石碑',
    'casement window': '平开窗',
    'shrine': '神龛',
    'cloud chamber': '云室',
    'ichor': '神血',
    'a being of wild and natural magic': '掌控野外自然魔力的存在',
    'immortal spirits of nature, even the weakest Kell are beings to rival wizards': '不朽的自然精神，甚至最弱的克尔都能直面巫师的竞争',
    'high kell': '高级克尔',
    'library': '图书馆',
    'gate': '门',
    'dhrunic gate': '传说中的门',
    'armory': '军械库',
    'archive': '档案室',
    'arcane archive': '奥术档案室',
    'orrery': '星象仪',
    'pond': '水塘',
    'Pond': '水塘',
    'starweb': '星网',
    'star shard': '星星碎片',
    'max star shard': '星星碎片上限',
    'dreams': '梦境',
    'max dreams': '梦境上限',
    'lexyrinth': '迷宫入口',
    'gargoyle': '石像鬼',
    'grotesque': '怪异石柱',
    'fountain': '喷泉',
    'fourposter': '四柱卧床',
    'campfire': '营火',
    'casket': '棺材',
    'clepsydra': '滴漏',
    'astral': '星空',
    'starfall': '星落',
    'lightning': '闪电',
    'zap': '快速打击',
    'An electric shock leaps from your fingers': '从你的手指发出一束电击',
    'fire bolt': '火焰箭',
    'fire dart': '火焰标枪',
    'frost bolt': '冰冻箭',
    'dark bolt': '暗影箭',
    'death bolt': '死亡之箭',
    'slumber': '睡眠',
    'dark magician': '黑暗魔法师',
    'magician': '魔法师',
    'steed': '骑乘',
    'servicing': '服♂务中',
    'Offer your magical services to the nearby townsfolk.': '为附近的城镇居民提供魔法服务。',
    'imbue mundane gems and items with magical properties.': '给宝石或其它物品灌输魔法属性。',
    'warlock': '邪恶男巫',
	'archlock': '邪恶大男巫',
    'reanimator': '复生者',
    'bonemonger': '骨术士',
    'dreadlord': '恐惧之王',
    'bonus damage': '伤害加成',
    'tohit bonus': '命中加成',
    'waif': '流浪者',
    'Common way to carry coins.': '最普遍的存钱方式。',
    'max spelllist': '法术列表上限',
    'blunt': '钝器',
    'you might not like what you catch.': '你大概不会喜欢它捕捉的东东。',
    'When I get a little money I buy books, and if any is left I buy food and clothes.': '当我赚钱了我就去买书，如果还有剩那我再买食物和衣服。',
    'performing': '表演中',
    'tricksource': '诡计来源',
    'a simple deck of cards': '简单的纸牌',
    'sufficiently advanced sleight of hand is indistinguishable from magic': '足够高端的手法与魔法是无法区分的',
    'Skip Warning': '跳过警告',
    'respectable': '可敬',
    'You have become a respected personage in the magical world.': '您已成为魔法世界中受人尊敬的人物。',
    'Your master has decided you are ready to take the next step on the path of wizardry.': '你的导师认为你已经准备好迈出巫术之路的下一步。',
    'Pest Control': '害虫防治',
    'After your daily castigation, your master mentions the rats in the basement have become a problem. Something about stolen shortswords and building barricades. You had better go down and deal with it.': '在对你例行斥责之后，你的导师提到地下室的老鼠已成问题。可能是指你偷的短剑和树立的路障。你最好下去处理它。',
    'A small crystal for performing optical experiments.': '用于进行光学实验的小晶体。',
    'Noting your progress, your master begrudgingly offers you some space in the attic.': '你的导师注意到你的进步，勉强在阁楼给你提供一些空间',
    'Don\'t let it go to your head.': '不要让它落到你的头上。',
    'it doesn\'t seem very nice.': '它看上去不是很友好',
    'Measure the stars.': '观测星星。',
    'A simple window to let in light and air.': '一个简单的窗户，可以让光线和空气进入。',
    'study of pure light': '对纯粹光明的研究',
    'the light fantastic': '梦幻般的光',
    'pulsing light': '光脉冲',
    'a small pulse of light zips around you, mending injuries.': '一小束光在您周围拉动，恢复伤势。',
    'Max Levels': '等级上限',
    'light spear': '光矛',
    'a barb of solid light': '有形的光形成的倒钩',
    'seeing the unseen': '看到看不见的东东',
    'Candle holder.': '火烛的台座',
    'virtuous': '善良的',
    'Your actions have shown you to be a virtuous wizard.': '您的行为表明您是一位善良的巫师。',
    'Rented room of a local Inn': '当地旅馆的出租房间',
    'Rented Room': '出租房间',
    'You are now living at a local inn, losing precious coins to pay the rent.': '您现在住在当地的旅馆里，需要花费宝贵的黄金来支付租金。',
    'Solitary Magic': '独立魔法师',
    'Some say the study of magic doesn\'t truly begin until apprenticeship ends. People say a lot of things.': '有人说，直到学徒制结束，魔术的研究才真正开始。他们话太多了。',
    'Your master behind you, you set off into the world alone. You had better find a new place to stay.': '你的导师离开了你，你独自一个人踏上了世界。你最好找到一个新的住宿地点。',
    'A remote hut in the woods.': '在树林里的一个偏僻的小屋。',
    'Cozy and quaint.': '舒适而古朴。',
    'a book of elvish symbols': '一本精灵符号的书',
    'through dungeons deep and caverns old': '穿过这深深的地牢啊，走过这远古的洞穴呵',
    'tend to sick and wounded animals in the wild': '在野外照料生病和受伤的动物',
    'expend your research to discover new sources of stamina.': '扩展您的研究以发现耐力的新来源。',
    'expend your research to enhance your durability.': '扩展您的研究以增强持久性。',
    'expend your research to enhance your mental fortitude.': '扩展您的研究以增强您的心灵能量。',
    'a pack to facilitate longer travels.': '方便长途旅行的背包。',
    'Focus of air magic.': '专注于空气魔法',
    'someone needs to have a talk with the sack-maker\'s guild.': '需要有人和制袋协会谈谈。',
    'orc camp': '兽人营地',
    'a scourge of cities.': '城市的祸害。',
    'ruined crypt': '毁灭地穴',
    'under den': '地下兽穴',
    'skittering caverns': '掠夺洞穴',
    'the only treasures here are were lost by adventurers searching for treasure.': '搜寻宝藏的冒险家错过了这里唯一的宝藏。',
    'an ancient crypt of crumbling stone.': '由崩裂的石头组成的古老地穴。',
    'proverbial den of thieves': '众所周知的贼窝',
    'spider slayer': '蜘蛛杀手',
    'Stand of burning hot coals.': '站在燃烧的热煤中',
    'An elegant latticed portal for letting in air and light.': '优雅的格子式门架可让空气和光线进入。',
    'A shrine to divine forces.': '神圣力量的神殿。',
    'A simple, bare cell.': '一个简单的，光秃秃的格子。',
    'a burning pyre for the practice of pyromancy.': '为练习火魔法而点燃的柴堆。',
    'be careful where you put it.': '小心那个地方',
    'Flee': '逃跑',
    'enc': '遭遇',
    'Small bag keeps gems safe without scratching.': '小袋子可确保宝石安全无刮擦。',
    'A crystal sphere revealing distant lands.': '水晶球里可以看到遥远的土地。',
    'sealing light': '光缝合',
    'seams of light close your wounds.': '用光缝合伤口',
    'plantsource': '植物来源',
    'favored pursuit': '首选爱好',
    'max pursuits': '爱好上限',
    'Mark an activity as a pursuit to return to in idle moments.': '标记一个行动为爱好，当你空闲时自动执行（译者注：购买后，点击右侧行动条的F按钮标记爱好）',
    'reset hall': '重置大厅',
    'astral lore': '星空学识',
    'Attune (elements': '调和 (元素',
    'somnambulist': '梦游者',
    'energy': '能源',
    'life pool': '生命池',
    'Items can only be enchanted with enchantments of equal or lower level.': '物品的可附魔的等级不高于该物品等级',
    'channel spirits for a small fee.': '付一点费用就可以引导精神',
    'A small but solid chest.': '一个小而坚固的箱子',
    'bright vista': '明亮远景',
    'a small knoll reveals lands far into the distance': '一个小丘陵展现了远方的土地',
    'Professional Magick': '专业魔法师',
    'Every province has its handful of runaway apprentices and failed Adepts. It\'s not uncommon for thieves and rangers to know a spell or two. They are nothing compared to the talents of a true professional.': '每个领域都有少数落跑的学徒和失败的熟练者。贼和流浪汉知道一两个法术并不少见。与真正的专业人员的才华相比，他们算不了什么。',
    'elementalist': '元素法师',
    'max elemental': '元素能力上限',
    'elemental exp': '元素能力经验',
    'arcane alembic': '奥术净化器',
    'arcane alembic arcane gem': '奥术净化器奥术宝石',
    'binding circle': '束缚圈',
    'sand garden': '沙漠园林',
    'treasure room': '藏宝室',
    'gabled mansion': '山窗宅第',
    'half-timber house': '半木制房屋',
    'a compiliation of obscure demonic languages': '晦涩的恶魔语言汇编',
    'a complex alchemical process drips arcane energy onto gemstones.': '一个会将奥术能量滴到宝石上的复杂炼金工艺。',
    'A modest house in a small town.': '小镇里的普通房子',
    'A quiet inn for hosting wayfarers.': '一个接待旅人的安静旅馆。',
    'A primitive dwelling well-suited to particular areas of study. Others less so.': '非常适合特定研究领域的原始住所，其它方面则不足。',
    'A small shop in a bustling city.': '繁华城市里的小商店。',
    'A vast home of rustic design': '质朴设计的广阔家园',
    'A spacious house with many gabled windows.': '带有许多山墙窗户的宽敞房屋。',
    'magic circle for binding summoned entities': '约束召唤物的魔法圈',
    'A rough but sturdy bookcase.': '粗糙但坚固的书架。',
    'A chamber of swirling vapours for study.': '用于学术研究的涡流蒸汽室',
    'a quickly growing plant': '快速生长的植物',
    'Runed table for enchanting': '用于附魔的符文桌',
    'Water Fountain': '喷水的泉',
    'a fountain issues from the stone demon\'s mouth': '从石制恶魔像里喷水',
    'A resting place for the dead.': '死者休息的地方',
    'a grim, disfigured stone statue': '阴冷怪异的石像',
    'A large room for accumulated treasures.': '藏有宝藏的大房间。',
    'A safe space for treasure.': '保存财宝的安全空间。',
    'A space suitable for crafting and enchanting items.': '一个适合制作和附魔物品的空间。',
    'small wooden bed.': '小型的木质床',
    'Saferoom for ancient sources of magic.': '为魔法的古老来源打造的宝库。',
    'rocks and sand form patterns of intricate design.': '岩石和沙子形成复杂设计的图案。',
    'Arcane Ascendant': '奥术支配者',
    'The masses of arcane dabblers never reach such heights.': '大部分奥术涉猎者从未达到的高度。',
    'potions room': '草药屋',
    'room for preparing and brewing potions': '准备和酿造药水的房屋',
    'Magical Mastery': '魔法精通者',
    'You are a master of your field of magic.': '你是魔术领域的大师。',
    'Supreme Sorcery': '法术至高者',
    'Not even the masters could challenge you.': '甚至大师们也不能挑战你。',
    'attune to primal forces of the world.': '调和世界上的原始力量。',
    'Spin straw into gold': '把石头戳成金子',
    'leech blood from a body to restore your health': '从尸体内吸取血液以恢复生命',
    'an incidental necessity to the advancement of magic': '为了魔法事业发展的偶然需要',
    'why do they come to me to die?': '他们为什么来找我送死呢？',
    'Experiment on dead or soon-to-be-dead subjects. This is not something a good wizard would do.': '对死亡或即将死亡的受试者进行实验。 这不是一个好的魔法师会做的事情。',
    'oversee the funerary rites of merchants and nobles.': '主持商人和贵族的葬礼。',
    'bind a soul within a spirit gem.': '将灵魂束缚在精神宝石中。',
    'undertake a quest to subdue a great evil.': '征服邪恶大恶魔的任务。',
    'Travel the wide world.': '环游世界。',
    'Craft a gem from raw minerals.': '用原始矿物制成宝石。',
    'magic over matter': '魔法高于物质',
    'gemimbue perpetual': '灌输宝石持续',
    'gemimbue length': '灌输宝石时长',
    'sorcerer': '元素巫师',
    'Dhrunic Magic': '传说魔法师',
    'Magic from a forgotten age.': '来自被遗忘时代的魔法。',
    'serenity': '宁静',
    'Brew': '调制',
    'timegem': '时之宝石',
	"Gem imbued with raw spirit.": '充满了原始精神的宝石',
	"Gem imbued with the essence of air.": '充满了空气本质的宝石',
	"Gem imbued with the essence of darkness.": '充满了黑暗本质的宝石',
	"Gem imbued with the essence of earth.": '充满了土地本质的宝石',
	"Gem imbued with the essence of fire.": '充满了火焰本质的宝石',
	"Gem imbued with the essence of light.": '充满了光明本质的宝石',
	"Gem imbued with the essence of water.": '充满了水本质的宝石',
	"Gem infused with arcane energy.": '充满了奥术能量的宝石',
    'crafted from gems which do not yet exist.': '由尚未产出的宝石制成。',
    'kell': '克尔',
    'avatar': '神灵化身',
    'An incarnation of raw, elemental forces.': '原始力量的化身。',
    'titles': '头衔',
    'spellspire': '法术尖塔',
    'dream chamber': '梦之屋',
    'timewell': '时间掌控',
    'expanded halls': '扩展大厅',
    'hallSize': '大厅大小',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '\n			Train': '训练',
    '\n			Stop': '停止',
    'No space remaining. Sell items or find a new Home.\n			': '没有剩余空间。 出售物品或找到新家。',
    '\n		Roll-over Item and hold {Shift} + {Number} to assign quickslot.': '滚动物品并按住{Shift} + {数字}可以分配快速插槽。',
    '\n		Press {Number} again to use quickslot Item.\n	': '再次按{数字}以使用快速插槽物品。',
    '\n		rest': '休息',
	
	//试验性功能，注意条件顺序
	'study': {
		'.action-btn': '学习',		//当前节点及其父节点有名为"action-btn"的class属性
		'.furniture': '书房',
		'$.menu-content>.main-actions': '学习',  //执行docment.querySelector(".menu-content>.main-actions")的结果不为null，即当前处于"主界面"页面
		'$.menu-content>.home-view': '书房',	//执行docment.querySelector(".menu-content>.home-view")的结果不为null，即当前处于"家"页面
	},
	'potions': {
		'.skill':'药剂学',
		'.menu-items':'药剂',
		'$.menu-content>.skills': '药剂学',
	},

    //原样
	"⚙": "⚙",
	"打开手机QQ": "打开手机QQ",
	"点击加群": "点击加群",
	"更多同类游戏": "更多同类游戏",
	"旧版": "旧版",
	"论坛": "论坛",
	"如右上版本号不对或其它异常问题请按Ctrl+F5刷新游戏": "如右上版本号不对或其它异常问题请按Ctrl+F5刷新游戏",
	"扫码加群": "扫码加群",
	"书房": "书房",
	"提示：游戏已更新至build#": "提示：游戏已更新至build#",
	"药剂学": "药剂学",
	"一次": "一次",
	"一起讨论吧": "一起讨论吧",
	"Git游戏": "Git游戏",
	"QQ群号": "QQ群号",
    '': '',
    '': '',
}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
	
	'Upgrade Unlocked: ': '升级解锁：',
	'Action Unlocked: ': '行动解锁：',
	'Resource Unlocked: ': '资源解锁：',
	'Class Unlocked: ': '课程解锁：',
	'Unlocked: ': '解锁：',
	'Locale Unlocked: ': '地点解锁：',
	'Furniture Unlocked: ': '家具解锁：',
	'Skill Unlocked: ': '技能解锁：',
	'Home Unlocked: ': '住房解锁：',
	'Dungeon Unlocked: ': '地牢解锁：',
	'Potion Unlocked: ': '药剂解锁：',
	'Enchant Unlocked: ': '附魔解锁：',
	'Spell Unlocked: ': '法术解锁：',
	'slot: ': '插槽：',
	'kind: ': '类型：',
	'Title Earned: ': '获得头衔：',
	'title: ': '头衔：',
	'protection: ': '防护：',
	'dot id: : ': '状态名称：',
	
	"🌳": "🌳",
	"📖": "📖",
	"🏰": "🏰",
	"⚔": "⚔",
	"⭐": "⭐",
	
	'dot ':'状态 '
	
	
}

//需处理的后缀
var cnPostfix = {
	' Improved': '已提升',
	
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
	
	'🎃': '🎃',
	"🎃:": "🎃：",
	"🌳": "🌳",
	"📖": "📖",
	"🏰": "🏰",
	"⚔": "⚔",
	"⭐": "⭐",
	
	', furniture': '，家具',
	', spiritsource': '，精神来源',
	', naturesource': '，自然来源',
	', pets': '，宠物',
	', shadowsource': '，暗影来源',
	', airsource': '，空气来源',
	', enchantsource': '，附魔来源',
	', garden': '，花园',
	', plantsource': '，植物来源',
	', home': '，家',
	', skill': '，技能',
	', school': '，学院派',
	', elemental': '，元素能力',
	', element': '，元素',

	', gold': '，黄金',
	', arcane gem': '，奥术宝石',
	', gems': '，宝石原石',
	', Tomes': '，著作',
	', Codices': '，手册',
	', scrolls': '，卷轴',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s+$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
];
var cnExcludePostfix = [
	/:?\s*\-?\d+(\.\d+)?\s*~\s*\d+(\.\d+)?/,  // : 1.5 ~ 2.5
	/:?\s*\d+\s*\/\s*\d+\s*/,	// : 13 / 14
	/:?\s*\d+(\.\d+)?,\s\+?\d+(\.\d+)?/, // : 0.1, +1
    /(🎃)?(🌳)?(📖)?:?\s*\(?[+\-]?x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
	/:?\s*\d+%\s*/, //12%
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    //[/^Usages: (\d+)\/$/, '用途：$1\/'],
    //[/^workers: (\d+)\/$/, '工人：$1\/'],
	[/^(.+)\sresist nature$/, '$1 自然抵抗'],
	[/^(.+)\sresist spirit$/, '$1 精神抵抗'],
	[/^(.+)\sresist shadow$/, '$1 暗影抵抗'],
	[/^(.+)\sresist undead$/, '$1 亡灵抵抗'],
	[/^(.+)\sresist poison$/, '$1 毒素抵抗'],
	[/^(.+)\sresist necrotic$/, '$1 死灵抵抗'],
	[/^(.+)\sresist air$/, '$1 气抵抗'],
	[/^(.+)\sbonuses air$/, '$1 气加成'],
	[/^(.+)\shits air$/, '$1 气命中加成'],
	[/^(.+)\sresist water$/, '$1 水抵抗'],
	[/^(.+)\sbonuses water$/, '$1 水加成'],
	[/^(.+)\shits water$/, '$1 水命中加成'],
	[/^(.+)\sresist fire$/, '$1 火抵抗'],
	[/^(.+)\sbonuses fire$/, '$1 火加成'],
	[/^(.+)\shits fire$/, '$1 火命中加成'],
	[/^(.+)\simmunities fire$/, '$1 火免疫'],
	[/^(.+)\sresist earth$/, '$1 土抵抗'],
	[/^(.+)\sbonuses earth$/, '$1 土加成'],
	[/^(.+)\sbonuses nature$/, '$1 自然加成'],
	[/^(.+)\sbonuses shadow$/, '$1 暗影加成'],
	[/^(.+)\sbonuses spirit$/, '$1 精神加成'],
	[/^(.+)\sbonuses mana$/, '$1 法力加成'],
	[/^(.+)\shits earth$/, '$1 土命中加成'],
	[/^(.+)\shits nature$/, '$1 自然命中加成'],
	[/^(.+)\shits shadow$/, '$1 暗影命中加成'],
	[/^(.+)\shits spirit$/, '$1 精神命中加成'],
	[/^(.+)\sresist cold$/, '$1 冰冷抵抗'],
	[/^(.+)\sresist light$/, '$1 光抵抗'],
	[/^(.+)\sresist holy$/, '$1 神圣抵抗'],
	[/^(.+)\stohit$/, '$1 命中'],
	[/^(.+)\sdefense$/, '$1 防御'],
	[/^(.+)\sLevel Up!$/, '$1 升级了！'],
]);
