http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
core.editor="C:\Users\a\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
user.name=Arith Undine
user.email=penuser0@gmail.com
gui.recentrepo=D:/Git/Wizrobe
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://gitee.com/likexia/Theory-of-Magic.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
gui.wmstate=normal
gui.geometry=841x483+820+450 189 218
user.email=5507470+Kiwaguro@user.noreply.gitee.com
user.name=Kiwaguro
